### ISSUE TITLE
能注入PUBG不？ WIN10 X64

### ISSUE THREAD

**Issue by snikeguo** [DragonQuestHero/Kernel_Inject#1]
RT

**Comment by DragonQuestHero** [comment]
可以 TP早就反掉了 BE稍微魔改下随便注
![qq 20180930033839](https://user-images.githubusercontent.com/21189903/48256727-73b93d80-e44b-11e8-9320-d85d952228ed.jpg)
![qq 20180930004856](https://user-images.githubusercontent.com/21189903/48256752-8764a400-e44b-11e8-91c9-e93a11dc98b9.png)
