### ISSUE TITLE
the project does not compile

### ISSUE THREAD

**Issue by xSanx** [DragonQuestHero/Kernel_Inject#3]
hi, i use Visual Studio 2019 and get this error : The specified executable file for the stampinf.exe task could not be started. System.IO.FileNotFoundException: File 'D: \ tmp \ inject \ Kernel_Inject-win10 \ Kernel_Inject \ Kernel_Inject.inf' not found. Help me please with your project. thank you

**Comment by VVVANNONVVVV** [comment]
Does anybody has solved it?

**Comment by DragonQuestHero** [comment]
delete Kernel_Inject.inf
